name: kinfolk
description: A new Flutter package for integration with CUBA Platform based backend.
version: 1.0.3
author: yeras-is <maihanov96@gmail.com>
homepage: https://github.com/yeras-is/kinfolk

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  oauth2: ^2.0.0
  hive: ^2.0.0
  hive_flutter: ^1.0.0

flutter:
